{% set version = "1.3.4" %}

package:
  name: datapackage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/datapackage/datapackage-{{ version }}.tar.gz
  sha256: c9ec33345aa95f3caec33204dc8de1cb14f780aa0f4b3014146bb70ad14615f1

build:
  number: 0
  noarch: python
  entry_points:
    - datapackage = datapackage.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cchardet >=1.0,<2.0
    - click >=6.7,<7.0
    - jsonpointer >=1.10,<2.0
    - jsonschema >=2.5,<3.0
    - requests >=2.8,<3.0
    - six >=1.10,<2.0
    - tableschema >=1.1.0,<2.0
    - tabulator >=1.3,<2.0
    - unicodecsv >=0.14,<2.0

test:
  imports:
    - datapackage
  commands:
    - datapackage --help
  requires:
    - pylama
    - tox

about:
  home: https://github.com/frictionlessdata/datapackage-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Utilities to work with Data Packages as defined on specs.frictionlessdata.io

extra:
  recipe-maintainers:
    - ocefpaf
