{% set version = "1.15.0" %}

package:
  name: datapackage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/datapackage/datapackage-{{ version }}.tar.gz
  sha256: 08042a9d3f8a003ee61161022d90e00e6536d6e7b3c45e8b3e64301c0e92e0e6

build:
  number: 0
  noarch: python
  entry_points:
    - datapackage = datapackage.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cchardet >=1.0
    - click >=6.7
    - jsonpointer >=1.10
    - jsonschema >=2.5
    - requests >=2.8
    - six >=1.10
    - tableschema >=1.1.0
    - tabulator >=1.24.2
    - unicodecsv >=0.14

test:
  imports:
    - datapackage
  commands:
    - pip check
    - datapackage --help
  requires:
    - pylama
    - tox
    - pip

about:
  home: https://github.com/frictionlessdata/datapackage-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Utilities to work with Data Packages as defined on specs.frictionlessdata.io

extra:
  recipe-maintainers:
    - ocefpaf
    - roll
