travis:
  secure:
    BINSTAR_TOKEN: qd5A4QUIdBuwTBDriyilhCIvP84ZfDO99WOR3qERLsscWI5kYyrMpEObgrRAZrkqW7grlPTHguiW2mmGJihUBsMuklA4vKlTjzZ7tEA3CrTXiEAboHIO8td7u7nG3rOTAhvMF2uAreQv6Pasya2s9qN7oPGWwACMlVzaU3cQixO1K7J6rHGWRv1zYhPTREbj1jzj0BTVFXOR2LbOoh5vOCvXGa5SSBvCrMnd2/T04MPsX6VXBVSLJOQ1RibdPHpMoefO7QKHwUQCVmvJ/HuGiHHfZaOW/adCJyJfpFLwAp0DhFJrh74Itjm/rDx86COwMDoznoW0OTfJfd8Sed8iuHYRsHVRjaXH5KQCYzOl+9vDozrTPs2wDiufs4nyo4btd4h8twGcu33QzvgqkC5KJNqSaYNpwvyX6dp4tWLopUunoqoTkfxVEIykh4VNFI78iWuwxxU964BtKEAcH0O0CRPvjAGvFceH7AsQZDRc1yg+dgfCIXOsSRLtOQRPLoxN0QConM0WWbjtO8d1gMnUO4f1PDkiXuTISlr/mA7gPMctZVrVMsOSmElGXQ3m4s/yOvMaekJ69rnzCNU9/Lt+d9vhwTjjIYyk2h0rLceDLl2ezELJioIK1qrcn9sABrEZakjWAj+sYKAF8lpABWJQTmM8ZuDGg6s6Z1ujuX1IaMk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
