travis:
  secure:
    BINSTAR_TOKEN: VqNvbEf98sEQjOEQuMy58347GSfRXJPCutLtfdC8CL3BMSsoQ56kGAx6rsCB7mdoFyG27NN1CvzPA6U6L5Ax4oGGB1hWKIp8E6R3rk/MFPEaZNKW6HgDMW226aRcAB+BDV1YvDAgSvwHT71iQc+jomzR1tNfxly0YiAwc+oTI/TmFT85cQWji5ANl99iD0Ekr6j3kICS4E1gqPqZqrD1QVX7K9923yHmQLdnOLzBd1gjcmbd9XEaHAoYwnjfUp1oDERaDAJPR+MGzVavNPBkU6rQLQ7Xn7sGgUJ10WlhxiEIyBHGv2UoqpBdH5VdK8Tvc0syIK+OB5ORhHr+NHhOk6QPYpVwGDNkiEQm1eqVLvkNEPJMhvNCQ2nWODWvWvZojWXIXTPSQSRC+7rmfbo5jCJl+xN5rZXH+4AeFL66VAsxOZvE39UoGeIiD8J3RKaL8J+GZD9L2zi1jsa4ptJl3+OEi7zDcI0KkGr6BihYa6hgD5a8mW3OnPqy9NWjGkAmBqJEUJubCsjcm9SE0CNLdBxN72VDn4vdfHJZVFcf88tCsK4JTNCyzCVfiBQEXx8hh6NnSMt13BnRNChdfjkuzvYI08h/j30X0AKTBCFovaERWy9HgPf7LnirO0CkJbKnMFR22loa63Zcj1La4LqEpC/gDbot4YIu8vYXzYjA2Zo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
